# Site settings
title: 刘易斯 - Lewis
description: 个人主页
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: 刘易斯 YISI LIU
user_description: Hello~ 我是一名C++后台开发程序员, 总是希望可以不断学习,不断成长. 我认可诸如天道酬勤之类的朴素道理. 长时间的工作, 心灵和身体一样, 会感到疲惫, 觉得缺乏意义与成就感, 闲时做些笔记, 写一些东西会让我觉得舒服许多. 这是我的博客地址 <a href="https://sonderease.github.io/lewis-blog.io/" target="_blank">EASE BLOG</a>
user_title: Software Engineer
email: 496167612@qq.com
# twitter_username: lorem_ipsum
github_username: SonderEASE
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
