# Site settings
title: 刘易斯 - Lewis
description: 个人主页
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: 刘易斯 - Lewis
user_description: Hi,我是一名后台开发程序员, 总是渴望能够不断地学习到新的技术~. 埋头工作,不停下脚步做一些总结的话, 会让我觉得缺少一些收获, 容易感到疲惫,焦躁和不安. 闲时做些笔记,写一些东西,会让我觉得感到轻松不少.这是我的博客地址 <a href="https://sonderease.github.io/lewis-blog.io/" target="_blank">SonderEASE's Blog</a> 欢迎交流学习~
user_title: Software Developer
email: sonderease@gmail.com
#twitter_username: SonderEASE
github_username:  SonderEASE
#gplus_username:  SonderEASE

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
